image:
  repository: pulumi/pulumi-kubernetes-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []

# Create a Secret to store your Pulumi access token for use by Stack CRDs
pulumiTokenSecret:
  # Set this to true and provide a token to create the secret
  create: false
  # Raw Pulumi token value
  token:
  # Name of the Secret to be created
  secretName: pulumi-access-token
  # Key that will contain the token
  secretKey: token

# Additional command arguments to pass to the controller
extraArgs:
  - --zap-level=error
  - --zap-time-encoding=iso8601

# Additional environment variables to pass to the controller
extraEnv:
  - name: OPERATOR_NAME
    value: "pulumi-kubernetes-operator"
  - name: GRACEFUL_SHUTDOWN_TIMEOUT_DURATION
    value: "5m"
  - name: MAX_CONCURRENT_RECONCILES
    value: "10"
  - name: PULUMI_INFER_NAMESPACE
    value: "1"

# Create operator RBAC
rbac:
  create: true

terminationGracePeriodSeconds: 300

nameOverride: ""

fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.

  name: pulumi-kubernetes-operator

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 8192m
    memory: 8192Mi
  limits:
    cpu: 8192m
    memory: 8192Mi    

nodeSelector: {}

tolerations: []

affinity: {}
