{{ if and .Values.pulumiTokenSecret.create .Values.pulumiTokenSecret.token }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.pulumiTokenSecret.secretName }}"
stringData:
  "{{ .Values.pulumiTokenSecret.secretKey }}": "{{ .Values.pulumiTokenSecret.token }}"
{{ end }}